project:
  type: book

book:
  title: "LIBE gm2"
  author: "Marco Garofalo"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - B48.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: default
    grid:
      sidebar-width: 250px
      body-width:    900px
      margin-width:  250px
      gutter-width:	 1.5em
    max-width: 2000px
    margin: 0
    #html-math-method: mathjax
    # include-in-header: mathjax.html
    html-math-method: katex
    # html-math-method: webtex
    # html-math-method:
    #   method: mathjax
    #   url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"